name: Create Baxos Project Resources

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/projects/baxos/**'
      - '.github/workflows/baxos_create_PROD.yml'
      - '.github/workflows/reusable_baxos_create.yml'
      - 'run.sh'
      - 'after_run.sh'
      - 'after_run_when_acr_changed.sh'
  schedule:
    - cron: '0 7 * * *'   # every day at 7 AM GMT to create resources
  workflow_dispatch: # Allows manual triggering

jobs:
  create_resources:
    uses: ./.github/workflows/reusable_baxos_create.yml
    with:
      environment: prod
      action: resourcesCreate
      projectName: baxos
      additionalArgs: "-A ./after_run.sh"
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID_PROD }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET_PROD }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID_PROD }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID_PROD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      BAXOS_SRC_PROJECT_GIT_REPO: ${{ secrets.BAXOS_SRC_PROJECT_GIT_REPO }}

      ACR_REGISTRY_NAME: ${{ secrets.ACR_REGISTRY_NAME_PROD }}

      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
      AZDO_TOKEN: ${{ secrets.AZDO_TOKEN }}
      AZDO_PIPELINE_ORGANIZATION: ${{ secrets.AZDO_PIPELINE_ORGANIZATION }}
      AZDO_PIPELINE_PROJECT: ${{ secrets.AZDO_PIPELINE_PROJECT }}
      AZDO_PIPELINE_NAME: ${{ secrets.AZDO_PIPELINE_NAME }}
