name: Create Baxos Project Resources

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/projects/baxos/**'
      - '.github/workflows/baxos_create_PROD.yml'
      - '.github/workflows/reusable_baxos_create.yml'
      - 'run.sh'
      #- 'bash/**'
  workflow_dispatch: # Allows manual triggering

jobs:
  create_resources:
    uses: ./.github/workflows/reusable_baxos_create.yml
    with:
      environment: prod
      action: resourcesCreate
      projectName: baxos
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID_PROD }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET_PROD }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID_PROD }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID_PROD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      BAXOS_SRC_GIT_ROOT_CREDS: ${{ secrets.BAXOS_SRC_GIT_ROOT_CREDS }}
      BAXOS_SRC_GIT_ROOT: ${{ secrets.BAXOS_SRC_GIT_ROOT }}
      BAXOS_SRC_GIT_PROJECT_SUFFIX: ${{ secrets.BAXOS_SRC_GIT_PROJECT_SUFFIX }}
