name: Create Baxos Project Resources

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/projects/baxos/**'
      - '.github/workflows/baxos_create_DEV.yml'
      - '.github/workflows/reusable_project_creation.yml'
      - 'run.sh'
      #- 'bash/**'
  workflow_dispatch: # Allows manual triggering

jobs:
  create_resources:
    uses: ./.github/workflows/reusable_project_creation.yml
    with:
      environment: prod
      action: resourcesCreate
      projectName: baxos
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID_PROD }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET_PROD }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID_PROD }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID_PROD }}
