name: Destroy Baxos Project Resources

on:
  schedule:
    - cron: '0 23 * * *'   # every day at 11 PM GMT to delete resources
  workflow_dispatch:

jobs:
  destroy_resources:
    uses: ./.github/workflows/reusable_baxos_create.yml
    with:
      environment: prod
      action: resourcesDelete
      projectName: baxos
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID_PROD }}
      ARM_CLIENT_CERT_BASE64: ${{ secrets.ARM_CLIENT_CERT_BASE64_PROD }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID_PROD }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID_PROD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      BAXOS_SRC_PROJECT_GIT_REPO: ${{ secrets.BAXOS_SRC_PROJECT_GIT_REPO }}
