name: Reusable Project Creation

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy (dev/prod)'
        required: true
        type: string
      action:
        description: 'Action to perform (e.g., resourcesCreate, resourcesDelete)'
        required: true
        type: string
      projectName:
        description: 'Name of the project (corresponds to folder in terraform/projects)'
        required: true
        type: string
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_TENANT_ID:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      BAXOS_SRC_PROJECT_GIT_REPO:
        required: false

jobs:
  execute_run_script:
    runs-on: ubuntu-latest
    env:
      MY_TERRAFORM_VERSION: 1.11.4
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # - name: Install dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y git curl

      - name: Set up tfenv and install Terraform
        run: |
          git clone https://github.com/tfutils/tfenv.git ~/.tfenv
          export PATH="$HOME/.tfenv/bin:$PATH" # Add tfenv to PATH for this step
          echo "$HOME/.tfenv/bin" >> $GITHUB_PATH # Add tfenv to GITHUB_PATH for subsequent steps
          tfenv install $MY_TERRAFORM_VERSION
          tfenv use $MY_TERRAFORM_VERSION
          terraform --version # Verify installation

      - name: Set up Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version # Verify installation

      - name: Execute run.sh
        env:
          FOLDER_ROOT: ${{ github.workspace }}
          LOG_VERBOSE: $${{ vars.LOG_VERBOSE }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          TF_VAR_BAXOS_SRC_PROJECT_GIT_REPO: ${{ secrets.BAXOS_SRC_PROJECT_GIT_REPO }}
        run: |
          ./run.sh -e ${{ inputs.environment }} -a ${{ inputs.action }} -p ${{ inputs.projectName }}
